# Deployment object
deployment:
  enabled: true
  name: helloworld
  namespace: default
  replicas: 1
  appName: helloworld
  role: api
  containerName: helloworld-container
  imageRepository: infrastructureascode/hello-world
  imageTag: latest
  port: 3004
service:
  enabled: true
  name: helloworld-service
  namespace: default
  appName: helloworld
  type: ClusterIP
  servicePort: 3004
  targetPort: 80
serviceAccount:
  enabled: true
  name: helloworld-account
  namespace: default
# Namespace object
namespace:
  enabled: false
# Ingress
ingress:
  enabled: false
